spring:
  profiles:
    active: prod

# 自定义配置
system:
  wx-config:
    appid: wx97dd8af79bb5f0f1
    secret: 6fc3dbe95cd3044ffc3e4e21920dd228
    token-to-live: 12h   #token 过期时间
    security-ignore-urls:
      - /api/wx/bind
      - /api/wx/checkBind
      - /api/wx/register
      - /api/wx/test

# mybatis配置
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.tencent.wxcloudrun.model
  configuration:
    #配置数据库字段和实体类名的自动映射关系，比如 user_name -> userName的映射
    map-underscore-to-camel-case: true
    #配置自生成主键，比如insert时
    use-generated-keys: true
